<?php
namespace Zepto\Extension;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-14 at 20:44:07.
 */
class TwigTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Twig
     */
    protected $twig;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->twig = new Twig();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zepto\Extension\Twig::getName
     */
    public function testGetName()
    {
        $this->assertEquals('Twig', $this->twig->getName());
    }

    /**
     * @covers Zepto\Extension\Twig::getFunctions
     */
    public function testGetFunctions()
    {
        $this->assertContainsOnly('Twig_SimpleFunction', $this->twig->getFunctions());
    }

}
