<?php
namespace Zepto\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-24 at 21:04:47.
 */
class PluginTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Plugin
     */
    protected $adapter;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->adapter = new Plugin(ROOT_DIR . 'tests/mocks');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zepto\Adapter\Plugin::read
     */
    public function testRead()
    {
        $this->adapter->read('SimplePlugin.php');
        $includes = get_included_files();
        $this->assertContains(ROOT_DIR . 'tests/mocks/SimplePlugin.php', $includes);
    }

    /**
     * @covers            Zepto\Adapter\Plugin::read
     * @expectedException PHPUnit_Framework_Error_Warning
     */
    public function testReadFailure()
    {
        $actual = $this->adapter->read('no_such_plugin');
        $this->assertFalse($actual);
    }

    /**
     * @covers            Zepto\Adapter\Plugin::read
     * @expectedException UnexpectedValueException
     */
    public function testReadPluginWithoutInterface()
    {
        $this->adapter->read('NoImplementInterfacePlugin.php');
    }
}
