<?php
namespace Zepto;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-03 at 13:49:12.
 */
class FileLoaderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var FileLoader
     */
    protected $loader;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->loader = new FileLoader(ROOT_DIR . 'content/');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $this->loader = null;
    }

    /**
     * @covers Zepto\FileLoader::__construct()
     * @covers Zepto\FileLoader::base_path()
     */
    public function testConstructWithPathThatHasNoTrailingForwardSlash()
    {
        $loader = new FileLoader(ROOT_DIR . 'content');
        $this->assertEquals(ROOT_DIR . 'content/', $loader->base_path());
    }

    /**
     * @covers Zepto\FileLoader::__construct()
     * @expectedException UnexpectedValueException
     */
    public function testConstructWithInvalidPath()
    {
        $loader = new FileLoader('!@£');
    }

    /**
     * @covers            Zepto\FileLoader::load()
     * @expectedException RuntimeException
     */
    public function testLoadInvalidFile()
    {
        $this->loader->load('@£@');
    }

    /**
     * @covers            Zepto\FileLoader::load()
     * @expectedException UnexpectedValueException
     */
    public function testLoadWithDirectory()
    {
        $this->loader->load('sub/');
    }

    /**
     * @covers       Zepto\FileLoader::load
     * @dataProvider providerTestLoadSingleFile
     */
    public function testLoadSingleFile($expected)
    {
        $actual = $this->loader->load('sub/page.md');
        $this->assertEquals($expected, $actual);
    }

    /**
     * @covers       Zepto\FileLoader::load()
     * @dataProvider providerTestLoadMultipleFiles
     */
    public function testLoadMultipleFiles($expected)
    {
        $actual = array_merge(
            $this->loader->load('sub/page.md'),
            $this->loader->load('sub/index.md')
        );

        $this->assertEquals($expected, $actual);
    }

    public function providerTestLoadSingleFile()
    {
        // $files['sub/page.md'] = '/*' . PHP_EOL
        //     . 'Title: Error 404' . PHP_EOL
        //     . 'Robots: noindex,nofollow' . PHP_EOL
        //     . '*/' . PHP_EOL . PHP_EOL
        //     . 'Error 404' . PHP_EOL
        //     . '=========' . PHP_EOL . PHP_EOL
        //     . 'Woops. Looks like this page doesn\'t exist.';

        $files['sub/page.md'] = '/*' . PHP_EOL
            . 'Title: Sub Page' . PHP_EOL
            . '*/' . PHP_EOL . PHP_EOL
            . '## This is a Sub Page' . PHP_EOL . PHP_EOL
            . 'This is page.md in the "sub" folder.' . PHP_EOL . PHP_EOL
            . 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.' . PHP_EOL . PHP_EOL
            . 'Donec ultricies tristique nulla et mattis.' . PHP_EOL . PHP_EOL
            . 'Phasellus id massa eget nisl congue blandit sit amet id ligula.' . PHP_EOL;

        return array(array( $files ));
    }

    /**
     * Data provider for tests
     * @return array
     */
    public function providerTestLoadMultipleFiles()
    {
        $files = array(
            'sub/page.md' => '/*' . PHP_EOL
                . 'Title: Sub Page' . PHP_EOL
                . '*/' . PHP_EOL . PHP_EOL
                . '## This is a Sub Page' . PHP_EOL . PHP_EOL
                . 'This is page.md in the "sub" folder.' . PHP_EOL . PHP_EOL
                . 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.' . PHP_EOL . PHP_EOL
                . 'Donec ultricies tristique nulla et mattis.' . PHP_EOL . PHP_EOL
                . 'Phasellus id massa eget nisl congue blandit sit amet id ligula.' . PHP_EOL
            ,
            'sub/index.md' => '/*' . PHP_EOL
                . 'Title: Sub Page Index' . PHP_EOL
                . '*/' . PHP_EOL . PHP_EOL
                . '## This is a Sub Page Index' . PHP_EOL . PHP_EOL
                . 'This is index.md in the "sub" folder.' . PHP_EOL . PHP_EOL
                . 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.' . PHP_EOL . PHP_EOL
                . 'Donec ultricies tristique nulla et mattis.' . PHP_EOL . PHP_EOL
                . 'Phasellus id massa eget nisl congue blandit sit amet id ligula.' . PHP_EOL
        );

        return array(array( $files ));
    }
}
