<?php
namespace Zepto;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-12 at 20:07:01.
 */
class HelperTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Helper
     */
    protected $helper;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zepto\Helper::default_config
     */
    public function testDefaultConfig()
    {
        $expected = array(
            'zepto' => array(
                'environment'       => 'dev',
                'content_dir'       => 'content',
                'plugins_dir'       => 'plugins',
                'templates_dir'     => 'templates',
                'default_template'  => 'base.twig',
                'content_ext'       => array('.md', '.markdown'),
                'plugins_enabled'   => true
            ),
            'site' => array(
                'site_root'         => 'http://localhost:8888/zepto/',
                'site_title'        => 'Zepto',
                'date_format'       => 'jS M Y',
                'excerpt_length'    => '50',
                'nav'               => array(
                    'class'             => 'nav',
                    'dropdown_li_class' => 'dropdown',
                    'dropdown_ul_class' => 'dropdown-menu'
                )
            ),
            'twig' => array(
                'charset'           => 'utf-8',
                'cache'             => 'cache',
                'strict_variables'  => false,
                'autoescape'        => false,
                'auto_reload'       => true
            )
        );
        $this->assertEquals($expected, Helper::default_config());
    }

    /**
     * @covers Zepto\Helper::validate_config()
     */
    public function testValidateConfig()
    {
        $config = Helper::default_config();
        $this->assertTrue(Helper::validate_config($config));
    }

    /**
     * @covers            Zepto\Helper::validate_config()
     * @expectedException InvalidArgumentException
     */
    public function testConfigWithInvalidContentDir()
    {
        $config = Helper::default_config();
        $config['zepto']['content_dir'] = 'no_such_dir';
        Helper::validate_config($config);
    }

    /**
     * @covers            Zepto\Helper::validate_config()
     * @expectedException InvalidArgumentException
     */
    public function testConfigWithInvalidPluginsDir()
    {
        $config = Helper::default_config();
        $config['zepto']['plugins_dir'] = 'no_such_dir';
        Helper::validate_config($config);
    }

    /**
     * @covers            Zepto\Helper::validate_config()
     * @expectedException InvalidArgumentException
     */
    public function testConfigWithInvalidTemplatesDir()
    {
        $config = Helper::default_config();
        $config['zepto']['templates_dir'] = 'no_such_dir';
        Helper::validate_config($config);
    }

    /**
     * @covers            Zepto\Helper::validate_config()
     * @expectedException InvalidArgumentException
     */
    public function testConfigWithInvalidDefaultTemplate()
    {
        $config = Helper::default_config();
        $config['zepto']['default_template'] = 'no_such_file';
        Helper::validate_config($config);
    }

    /**
     * @covers            Zepto\Helper::validate_config()
     * @expectedException InvalidArgumentException
     */
    public function testConfigWithInvalidSiteRoot()
    {
        $config = Helper::default_config();
        $config['zepto']['environment'] = 'production';
        $config['site']['site_root'] = 'fuck://this@should?fail';
        Helper::validate_config($config);
    }

    /**
     * @covers Zepto\Helper::url_for
     */
    public function testUrlFor()
    {
        $zepto    = new Zepto;
        $helper   = new Helper($zepto->app);
        $actual   = $helper->url_for('index.md');
        $expected = 'http://localhost:8888/zepto/';

        $this->assertEquals($expected, $actual);
    }

    /**
     * @covers Zepto\Helper::link_for
     */
    public function testLinkFor()
    {
        $zepto    = new Zepto;
        $helper   = new Helper($zepto->app);
        $actual   = $helper->link_for('index.md');
        $expected = '<a href="http://localhost:8888/zepto/"> Welcome </a>';

        $this->assertEquals($expected, $actual);
    }
}
