<?php
namespace Zepto;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-03 at 13:49:12.
 */
class MarkdownLoaderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var FileLoader
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FileLoader\MarkdownLoader();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $this->object = null;
    }

    /**
     * @covers Zepto\FileLoader\MarkdownLoader::load()
     * @expectedException Exception
     */
    public function testLoad()
    {
        $this->object->load('@£@', 'aa');
    }

    /**
     * @covers Zepto\FileLoader\MarkdownLoader::load
     * @todo   Implement testLoad().
     */
    public function testLoadSingleFile()
    {
        $files['404.md'] = array(
            'meta'    => array(
                'title'         => 'Error 404',
                'robots'        => 'noindex,nofollow'
            ),
            'content' => '<h1>Error 404</h1>' . PHP_EOL
                . '<p>Woops. Looks like this page doesn\'t exist.</p>'
        );

        $result = $this->object->load(ROOT_DIR . 'content/404.md', array('md'));
        $this->assertEquals($files, $result);
    }

    /**
     * @covers Zepto\FileLoader\MarkdownLoader::load()
     */
    public function testLoadMultipleFiles()
    {
        $files['sub/index.md'] = array(
            'meta'    => array(
                'title'         => 'Sub Page Index'
            ),
            'content' => '<h2>This is a Sub Page Index</h2>' . PHP_EOL
                . '<p>This is index.md in the "sub" folder.</p>' . PHP_EOL
                . '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>' . PHP_EOL
                . '<p>Donec ultricies tristique nulla et mattis.</p>' . PHP_EOL
                . '<p>Phasellus id massa eget nisl congue blandit sit amet id ligula.</p>'
        );

        $files['sub/page.md'] = array(
            'meta'    => array(
                'title'         => 'Sub Page'
            ),
            'content' => '<h2>This is a Sub Page</h2>' . PHP_EOL
                . '<p>This is page.md in the "sub" folder.</p>' . PHP_EOL
                . '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>' . PHP_EOL
                . '<p>Donec ultricies tristique nulla et mattis.</p>' . PHP_EOL
                . '<p>Phasellus id massa eget nisl congue blandit sit amet id ligula.</p>'
        );

        $result = $this->object->load(ROOT_DIR . 'content/sub', array('md'));
        $this->assertEquals($files, $result);
    }

}
