<?php
namespace Zepto;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-06 at 02:02:06.
 */
class RouterTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Router
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $_SERVER['DOCUMENT_ROOT']   = '/var/www';
        $_SERVER['SCRIPT_FILENAME'] = '/var/www/zepto/index.php';
        $_SERVER['SERVER_NAME']     = 'zepto';
        $_SERVER['SERVER_PORT']     = '80';
        $_SERVER['SCRIPT_NAME']     = '/zepto/index.php';
        $_SERVER['REQUEST_URL']     = '/zepto/index.php/bar/xyz';
        $_SERVER['REQUEST_URI']     = '/zepto/index.php/bar/xyz';
        $_SERVER['PATH_INFO']       = '/bar/xyz';
        $_SERVER['REQUEST_METHOD']  = 'GET';
        $_SERVER['QUERY_STRING']    = 'one=1&two=2&three=3';
        $_SERVER['HTTPS']           = '';
        $_SERVER['REMOTE_ADDR']     = '127.0.0.1';
        unset($_SERVER['CONTENT_TYPE'], $_SERVER['CONTENT_LENGTH']);

        $this->object = new Router;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zepto\Router::show_errors
     * @todo   Implement testShow_errors().
     */
    public function testShow_errors()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zepto\Router::hide_errors
     * @todo   Implement testHide_errors().
     */
    public function testHide_errors()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zepto\Router::default_route
     * @todo   Implement testDefault_route().
     */
    public function testDefault_route()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zepto\Router::run
     * @todo   Implement testRun().
     */
    public function testRun()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zepto\Router::dispatch
     * @expectedException Exception
     */
    public function testDispatchOnNonExistentRoute()
    {
        $this->object->dispatch();
    }

    /**
     * @covers Zepto\Router::dispatch
     */
    public function testDispatch()
    {
        $_SERVER['REQUEST_URL']     = '/zepto/index.php/get';
        $_SERVER['REQUEST_URI']     = '/zepto/index.php/get';

        $router = new Router;

        $callback = function() {
            echo '1';
        };
        $router->get('/get', $callback);
        $router->run();

        $this->assertTrue($router->dispatch());
    }

    /**
     * @covers Zepto\Router::execute
     * @todo   Implement testExecute().
     */
    public function testExecute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zepto\Router::route
     * @expectedException Exception
     */
    public function testRouteAddExistingRoute()
    {
        $callback = function() {
            echo '1';
        };
        $this->object->route('/hello', $callback);
        $this->object->route('/hello', $callback);
    }

    /**
     * @covers Zepto\Router::route
     */
    public function testRouteAdd()
    {
        $callback = function() {
            echo '1';
        };
        $this->object->route('/hello', $callback);

        $expected = array(
            'GET' => array(
                '#^/hello/$#' => $callback
            )
        );

        $actual = $this->object->get_routes();

        $this->assertEquals($expected, $actual);
    }

    /**
     * @covers Zepto\Router::get
     */
    public function testGetRouteAdd()
    {
        $callback = function() {
            echo '1';
        };
        $this->object->get('/get', $callback);

        $expected = array(
            'GET' => array(
                '#^/get/$#' => $callback
            )
        );

        $actual = $this->object->get_routes();

        $this->assertEquals($expected, $actual);
    }

    /**
     * @covers Zepto\Router::post
     */
    public function testPostRouteAdd()
    {
        $callback = function() {
            echo '1';
        };
        $this->object->post('/post', $callback);

        $expected = array(
            'POST' => array(
                '#^/post/$#' => $callback
            )
        );

        $actual = $this->object->get_routes();

        $this->assertEquals($expected, $actual);
    }

}
