<?php
namespace Zepto;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-06 at 02:02:06.
 */
class RouterTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Router
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $_SERVER['DOCUMENT_ROOT']   = '/var/www';
        $_SERVER['SCRIPT_FILENAME'] = '/var/www/zepto/index.php';
        $_SERVER['SERVER_NAME']     = 'zepto';
        $_SERVER['SERVER_PORT']     = '80';
        $_SERVER['SCRIPT_NAME']     = '/zepto/index.php';
        $_SERVER['REQUEST_URL']     = '/zepto/index.php/bar/xyz';
        $_SERVER['REQUEST_URI']     = '/zepto/index.php/bar/xyz';
        $_SERVER['PATH_INFO']       = '/bar/xyz';
        $_SERVER['REQUEST_METHOD']  = 'GET';
        $_SERVER['QUERY_STRING']    = 'one=1&two=2&three=3';
        $_SERVER['HTTPS']           = '';
        $_SERVER['REMOTE_ADDR']     = '127.0.0.1';
        unset($_SERVER['CONTENT_TYPE'], $_SERVER['CONTENT_LENGTH']);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zepto\Router::run
     */
    public function testRun()
    {
        $_SERVER['REQUEST_URL']     = '/zepto/index.php/get';
        $_SERVER['REQUEST_URI']     = '/zepto/index.php/get';

        $router = new Router;

        $callback = function() {
            echo 'Successful run';
        };
        $router->get('/get', $callback);

        $expected = array(
            'callback'       => $callback,
            'params'         => array('/get/'),
            'route'          => '#^/get/$#',
            'original_route' => '/get'
        );

        $actual = $router->run();

        $this->assertEquals($expected, $actual);
    }

    /**
     * @covers Zepto\Router::run
     */
    public function testRunWithParameters()
    {
        $_SERVER['REQUEST_URL']     = '/zepto/index.php/get/random_value';
        $_SERVER['REQUEST_URI']     = '/zepto/index.php/get/random_value';

        $router = new Router;

        $callback = function($var) {
            echo $var;
        };
        $router->get('/get/<:random_var>', $callback);

        $expected = array(
            'callback'       => $callback,
            'params'         => array('/get/random_value/', 'random_value'),
            'route'          => '#^/get/(?P<random_var>[A-Za-z0-9\-\_]+)/$#',
            'original_route' => '/get/<:random_var>'
        );

        $actual = $router->run();

        $this->assertEquals($expected, $actual);
    }

    /**
     * @covers Zepto\Router::run
     * @expectedException Exception
     */
    public function testRunOnNonexistentRoute()
    {
        $_SERVER['REQUEST_URL']     = '/zepto/index.php/get';
        $_SERVER['REQUEST_URI']     = '/zepto/index.php/get';

        $router = new Router;

        $expected = array(
            'callback'       => '',
            'params'         => array('/get/'),
            'route'          => '#^/get/$#',
            'original_route' => '/get'
        );

        $actual = $router->run();
    }

    /**
     * @covers Zepto\Router::execute
     */
    public function testExecute()
    {
        $_SERVER['REQUEST_URL']     = '/zepto/index.php/get';
        $_SERVER['REQUEST_URI']     = '/zepto/index.php/get';

        $router = new Router;

        $callback = function() {
            return 'Successful GET';
        };
        $router->get('/get', $callback);

        $callback = function() {
            return 'Shit! A 404';
        };
        $router->get('/404', $callback);

        $expected = 'Successful GET';
        $actual   = $router->execute();

        $this->assertEquals($expected, $actual);
    }

    /**
     * @covers Zepto\Router::execute
     */
    public function testExecute404()
    {
        $_SERVER['REQUEST_URL']     = '/zepto/index.php/unknown_url';
        $_SERVER['REQUEST_URI']     = '/zepto/index.php/unknown_url';

        $router = new Router;

        $callback = function() {
            return 'Successful GET';
        };
        $router->get('/get', $callback);

        $callback = function() {
            return 'Shit! A 404';
        };
        $router->get('/404', $callback);

        $actual   = $router->execute();
        $this->assertFalse($actual);
    }

    /**
     * @covers Zepto\Router::route
     * @expectedException Exception
     */
    public function testRouteAddExistingRoute()
    {
        $router = new Router;

        $callback = function() {
            echo '1';
        };
        $router->route('/hello', $callback);
        $router->route('/hello', $callback);
    }

    /**
     * @covers Zepto\Router::route
     */
    public function testRouteAdd()
    {
        $router = new Router;

        $callback = function() {
            echo '1';
        };
        $router->route('/hello', $callback);

        $expected = array(
            'GET' => array(
                '#^/hello/$#' => $callback
            )
        );

        $actual = $router->get_routes();

        $this->assertEquals($expected, $actual);
    }

    /**
     * @covers Zepto\Router::get
     */
    public function testGetRouteAdd()
    {
        $router = new Router;

        $callback = function() {
            echo '1';
        };
        $router->get('/get', $callback);

        $expected = array(
            'GET' => array(
                '#^/get/$#' => $callback
            )
        );

        $actual = $router->get_routes();

        $this->assertEquals($expected, $actual);
    }

    /**
     * @covers Zepto\Router::post
     */
    public function testPostRouteAdd()
    {
        $router = new Router;

        $callback = function() {
            echo '1';
        };
        $router->post('/post', $callback);

        $expected = array(
            'POST' => array(
                '#^/post/$#' => $callback
            )
        );

        $actual = $router->get_routes();

        $this->assertEquals($expected, $actual);
    }

    /**
     * @covers Zepto\Router::get_routes()
     */
    public function testGetRoutes()
    {
        $router = new Router;

        $post_callback = function() {
            echo '1';
        };
        $router->post('/post', $post_callback);

        $get_callback = function() {
            echo '1';
        };
        $router->get('/get', $get_callback);

        $expected = array(
            'GET' => array(
                '#^/get/$#' => $get_callback
            ),
            'POST' => array(
                '#^/post/$#' => $post_callback
            )
        );

        $actual = $router->get_routes();
        $this->assertEquals($expected, $actual);
    }
}
