<?php
namespace Sonic;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-30 at 20:18:22.
 */
class RouteTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Route
     */
    protected $route;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->route = new Route('/get/<:id|[0-9]>', function() {
            return 'Test callback';
        });
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Sonic\Route::execute()
     */
    public function testExecute()
    {
        $actual = $this->route->execute();
        $this->assertEquals('Test callback', $actual);
    }

    /**
     * @covers Sonic\Route::url()
     */
    public function testUrl()
    {
        $actual = $this->route->url();
        $this->assertEquals('/get/<:id|[0-9]>', $actual);
    }

    /**
     * @covers Sonic\Route::pattern()
     */
    public function testPattern()
    {
        $actual = $this->route->pattern();
        $this->assertEquals('#^/get/(?P<id>[0-9])/$#', $actual);
    }

    /**
     * @covers Sonic\Route::callback()
     */
    public function testCallback()
    {
        $actual = $this->route->callback();
        $this->assertInstanceOf('Closure', $actual);
    }
}
